//! Agent guide files written into every project folder.
//!
//! `AGENTS.md` is the canonical guide (read by Codex, OpenCode, Aider, ...).
//! `CLAUDE.md` and `GEMINI.md` import it so Claude Code and Gemini CLI pick
//! it up automatically. Files that the user has edited (no generated marker)
//! are left alone.

use crate::folder::Folder;
use anyhow::Result;

const MARKER: &str = "<!-- rosaclef:generated";

/// Write the guides into `folder`. `exe` is how the `rosaclef` command is
/// reached (the path of the executable, or just `rosaclef`).
pub fn write(folder: &Folder, exe: &str) -> Result<()> {
    let body = agents_md(exe);
    put(folder, "AGENTS.md", &body)?;
    let pointer = format!(
        "{MARKER} — regenerated by the studio; delete this line to keep your own edits -->\n\
         # Rosaclef project\n\n\
         This folder is a Rosaclef music project. Read and follow AGENTS.md:\n\n@AGENTS.md\n"
    );
    put(folder, "CLAUDE.md", &pointer)?;
    put(folder, "GEMINI.md", &pointer)?;
    Ok(())
}

fn put(folder: &Folder, name: &str, text: &str) -> Result<()> {
    let path = folder.dir.join(name);
    if let Ok(existing) = folder.fs.read_to_string(&path) {
        if !existing.starts_with(MARKER) {
            return Ok(()); // user-owned
        }
    }
    Ok(folder.fs.write_if_changed(&path, text)?)
}

pub fn agents_md(exe: &str) -> String {
    let catalog = rosaclef_core::catalog_markdown();
    GUIDE
        .replace("{{EXE}}", exe)
        .replace("{{CATALOG}}", &catalog)
        .replace("{{PRESETS}}", &rosaclef_core::presets_markdown())
        .replace("{{MARKER}}", MARKER)
}

const GUIDE: &str = r##"{{MARKER}} — regenerated by the studio; delete this line to keep your own edits -->
# Rosaclef project — guide for coding agents

You are working inside a **Rosaclef** music project, next to a human producer who
has the Rosaclef studio (an FL Studio–style DAW) open in their browser. You are the
studio's resident assistant: you compose, arrange, sound-design and mix by editing
the project data. **The studio watches the files in this folder and updates live** —
the producer sees and hears every change you save within a fraction of a second.

## Files

| path | what |
|---|---|
| `project.json` | **The song.** Everything: tempo, instruments, patterns, arrangement, mixer. Edit this. |
| `project.schema.json` | JSON Schema (draft 2020-12) for `project.json`. |
| `.rosaclef/context.json` | What the producer is doing *right now* (see "The producer's context" below). Schema: `.rosaclef/context.schema.json`. |
| `.rosaclef/mixcheck.schema.json` | JSON Schema of `rosaclef mixcheck`'s report. |
| `.rosaclef/status.json` | Result of the studio's last load of `project.json` (`ok` + `issues`). Check it after every edit. |
| `samples/` | Audio files (wav/flac/mp3/ogg) used by `sampler` instruments and audio clips. |
| `renders/` | Exported mixdowns. |

## The producer's context

The studio continuously rewrites `.rosaclef/context.json` (read-only for you)
with what the producer is doing. **Read it whenever they say "this", "here",
"these notes", "the selected…", "what I just did", or refer to a part of the
song without naming it.** Fields (full schema in `.rosaclef/context.schema.json`):

- `focus` — panel they last touched: `playlist`, `score`, `channel rack`, `piano roll`, `voice to notes`, `mixer`, `browser`, `agent`.
- `transport` — `playing`, `mode` (`song` / `pattern`), playhead `positionBeats` and `position` (`bar:beat:tick`), `bpm`.
- `selection` — the selected `pattern`, `channel`, mixer `insert` and playlist `track`; `notes`
  (selected notes of the selected pattern, each with its `index` in that pattern's `notes`) and
  `clips` (selected clips with their `index` in `playlist.clips`), and `automation` (the selected
  automation lane — `index` in `automation`, `id`, `target`, selected `points` with their index,
  `valueAtPlayhead` — or null).
- `visible` — what is on screen: the playlist's beat range and tracks, and (when the piano roll is
  open) its pattern, channel, beat range and pitch range. "This part" usually means this range.
  With the Score view's **Film** open, `film` is the scene at the playhead: `shot` (its index in
  `animation.shots`, or null for the director's own), `selectedShot`, its beats, `frame`, framed
  channels (`focus`) and `why` — "this shot" is `selectedShot`, else `shot`.
- `recentEdits` — the producer's latest manual edits in plain words, newest last
  (e.g. `pattern "groove": +1 note on "snare" (D3 at beat 2.5)`, `channel "bass": cutoff 1200 → 900`).
  Your own edits to `project.json` are not listed.
- `seq` / `updatedAt` — increase on every write; compare them to know whether it changed.

Example:

```json
{
  "seq": 41, "updatedAt": "2026-09-29T21:14:03Z",
  "focus": "piano roll", "dock": "piano roll",
  "transport": { "playing": false, "mode": "pattern", "positionBeats": 2, "position": "001:03:00", "bpm": 92 },
  "selection": {
    "pattern": { "id": "keys", "name": "Keys", "length": 16, "noteCount": 80 },
    "channel": { "id": "keys", "name": "Rhodes", "instrument": "fm", "mixer": 4 },
    "insert": { "index": 4, "name": "Keys" }, "track": { "index": 2, "name": "Keys" },
    "notes": [ { "index": 12, "note": { "channel": "keys", "pitch": 63, "start": 2.5, "length": 1, "velocity": 0.72 } } ],
    "clips": []
  },
  "visible": {
    "playlist": { "startBeat": 0, "endBeat": 37, "firstTrack": 0, "lastTrack": 7 },
    "pianoRoll": { "pattern": "keys", "channel": "keys", "startBeat": 0, "endBeat": 11.3, "lowPitch": 55, "highPitch": 74 }
  },
  "recentEdits": [ { "at": "2026-09-29T21:13:58Z", "summary": "pattern \"keys\": edited 1 note (C4 at beat 2.5 → D♯4 at beat 2.5)" } ]
}
```

Indexes refer to `project.json` as it was when the context was written; re-read the project before
editing, and prefer matching notes by their content if the project changed since.

## Workflow

1. Read `.rosaclef/context.json` (what the producer is doing) and `project.json`
   (or run `rosaclef summary` for an overview).
2. Edit `project.json` directly — small, targeted edits. Keep the file's formatting style
   (one note per line); the studio rewrites it canonically on its next save anyway.
3. Validate: `rosaclef validate` (exit status 0 = ok). Errors name the exact JSON path, e.g.
   `patterns[2].notes[14].pitch: value 130 is outside the allowed range 0..127`.
   If the file is invalid the studio keeps playing the last good version and shows
   the producer the errors, so fix them promptly.
4. Critique: `rosaclef critic` lints the song against production rules of thumb (muddy
   voicings, notes out of key or beyond an instrument's range, robotic velocities, loopitis, a
   panned bass, the master limiter, ...). Look at what your edit added; apply a fix with
   `rosaclef critic --fix KEY` (or by rule id), or change the notes yourself. Findings the
   producer suppressed (`critic` in `project.json`) are deliberate: leave them alone.
5. Tell the producer briefly what you changed (they can undo any change in the studio with Ctrl+Z).

The producer may be editing in the UI at the same time. Always re-read `project.json`
right before editing it, and never rewrite the whole file from memory.

### Command line tools

`rosaclef` is on your PATH (`{{EXE}}`):

- `rosaclef validate` — check `project.json`.
- `rosaclef summary` — compact overview of channels, patterns, arrangement and mixer.
- `rosaclef critic` — the Critic's findings (`--json` with each fix as JSON Patch operations;
  `--fix KEY|RULE|all` applies fixes; `--suppress` / `--unsuppress KEY|RULE` hides a finding or
  turns a check off in `project.json`; `--enable` / `--disable RULE` turns a check on or off — the
  classical theory checks (keys, counterpoint, singable melodies) start off; `--rules` lists the
  checks). The studio's Critic tab shows the same findings.
- `rosaclef catalog` — every instrument/effect and its parameters (also below).
- `rosaclef presets [TYPE|NAME]` — factory presets; with a name, prints the instrument JSON.
- `rosaclef render [--pattern ID --loops N] [--out renders/x.wav]` — offline mixdown to WAV
  (prints duration, peak and RMS — useful to check levels without listening).
- `rosaclef mixcheck` — **mix diagnostics from one render**, as JSON (`--text`: ≤ 40 lines). Use it
  instead of rendering WAVs and parsing them, soloing parts or copying the project. For any range
  (`--range 52:59` bars as the producer counts them, `--beats 196:228`, `--section Chorus`; a
  repeated bar is reported once per pass) it measures: loudness (LUFS integrated / short-term /
  momentary), true peak, the peak *before* the master limiter and every compressor's and limiter's
  gain reduction, PLR/LRA, phase correlation, the spectrum, each part's level against the mix and
  how audible it is under the others (a masking model: `audibleFractionPct`, `maskedBy`). `findings`
  are ranked, each with a JSON Patch `fix` to the mixer (faders, EQ, dynamics, automation — never the
  notes: clashing notes are the Critic's, `rosaclef critic`); elements carry `suggestions` with the
  predicted effect.
  `--what-if '[{"op":"replace","path":"/mixer/inserts/4/volume","value":0.5}]'` (or `@file.json`)
  measures a change without writing it (the report gets `whatIf` with the differences; that report's
  own fixes are for the patched project); `--verify` re-measures each finding's fix (`verified.resolved`,
  `still`) and each suggestion. Fixes name the setting at fault (a limiter's drive, an EQ boost, a fader
  above unity); the song's lead (`"lead": true`) is also `buried` when it sits 10 LU under the mix, over the
  range or only in some sections (`buriedIn` lists the bars; an automation lane holding it down there is
  named and put back). Every part has `bySection` (its level against the mix per section) and, where
  it drops out (10 dB under its own level), `buriedIn` and a `part-dropout` finding naming the lane
  that holds it down. Also `--by bar|section|8-beats` (`--by section --text`: each part's level per
  section), `--focus rbass,4,master`,
  `--checks levels,audibility,masking,dynamics,gainreduction,spectrum,stereo`,
  `--target spotify|apple|youtube|ebu-r128|…`, `--reference samples/ref.wav` (level-matched A/B),
  `--history`, `--compare A.json B.json`, `--threshold strict|loose`, `--max-findings N`.
  Renders are cached (a repeated question is instant). Exit status 0 = no warnings, 1 = warnings,
  2 = error. `rosaclef mixcheck --schema` prints the report's JSON Schema. Recipes:
  - *Is X audible in bars A–B?* `rosaclef mixcheck --range A:B --focus X --checks levels,audibility,masking`
    → `elements[0].verdict`, `audibility.audibleFractionPct`, `maskedBy` (who covers it, where), and
    `suggestions[].patch`; try one with `--what-if` before editing.
  - *Why is section C squashed?* `rosaclef mixcheck --section C --checks levels,dynamics,gainreduction`
    → `master.preLimiterPeakDbfs` (> 0: the limiter is fighting), `limiterGainReductionDb`, `plrDb`,
    `perBar[].topContributors`, and the `master-overload` / `limiter-pumping` findings with their fixes.
  - Every finding is also a Critic rule: `rosaclef critic --audio` lists them; `--fix KEY` applies one.
- `rosaclef note --channel ID --pitch 60 --seconds 2 --out samples/x.wav` — synthesize one note
  of a channel's instrument (or `--instrument '{"type":"drum","options":{"kind":"clap"}}'`) into a sample.
- You may also create samples any other way (e.g. write a WAV with Python) into `samples/`.
- `rosaclef grooves` — the drum grooves; `rosaclef drums [--groove ID] [--guess]` — write the
  song's drum part (see **Drums** below).
- `rosaclef import-midi FILE.mid --name NAME --library ..` / `rosaclef import-lmms FILE.mmpz ...` —
  turn a MIDI file or an LMMS project into a new project next to this one (prints what was approximated).
  To add a MIDI file's parts to *this* song instead: `curl -X POST --data-binary @FILE.mid "$ROSACLEF_URL/api/import-midi?into=current"`.

HTTP API (while the studio runs, base URL in `$ROSACLEF_URL`): `POST /api/mixcheck` (the mixcheck
flags as JSON: `{"range": "52:59", "focus": ["rbass"], "whatIf": [...]}`; same report; the producer's
Mix check panel shows it; or `POST /api/jobs/mixcheck` with the same body answers `{"job": ID}` at once,
and `GET /api/jobs/ID` says how far it has come until its `state` is `"done"` with the `result` —
`POST /api/jobs/render` too), `GET /api/project`,
`PUT /api/project` (full document; validated), `GET /api/schema`, `GET /api/catalog`,
`GET /api/projects` (the library), `GET /api/files` (this project's files).
Editing the file is preferred. The producer can open another project from the studio; when
that happens your terminal session is restarted in the new project's folder.

## Data model

All **times are in beats** (quarter notes): `start: 4` is the downbeat of bar 2 in 4/4,
`0.25` is a 16th note, `0.5` an 8th, `1` a quarter. **Pitches are MIDI numbers**:
60 = C4 (middle C), 61 = C#4, 69 = A4; +12 = one octave up.
Velocities, volumes and most mix values are 0..1 (volumes are linear gain, 1.0 = 0 dB).

```jsonc
{
  "$schema": "./project.schema.json",
  "format": "rosaclef/1",
  "meta": { "title": "Velvet Hour", "author": "", "description": "" },
  "transport": { "bpm": 118, "beatsPerBar": 4, "swing": 0.12 },   // swing: 0 straight .. 1 triplet (16ths); optional "transpose": -12..12 semitones
  "channels": [                                     // the channel rack: one instrument each
    { "id": "kick", "name": "Kick", "color": "#d4af37",
      "instrument": { "type": "drum", "params": { "tone": 0.35 }, "options": { "kind": "kick" } },
      "volume": 0.9, "pan": 0, "mute": false, "mixer": 1 }  // mixer = insert index
  ],
  "patterns": [                                     // notes for any number of channels
    { "id": "groove", "name": "Groove", "color": "#d4af37", "length": 4,
      "notes": [
        { "channel": "kick", "pitch": 60, "start": 0, "length": 0.25, "velocity": 0.95 },
        { "channel": "kick", "pitch": 60, "start": 1, "length": 0.25, "velocity": 0.95 }
      ] }
  ],
  "playlist": {                                     // the arrangement
    "tracks": [ { "name": "Drums", "mute": false } ],
    "clips": [
      { "pattern": "groove", "track": 0, "start": 0, "length": 32 },           // pattern clip (loops the pattern)
      { "sample": "samples/vox.wav", "track": 1, "start": 16, "length": 8,     // audio clip
        "offset": 0, "gain": 1, "mixer": 7 }
    ]
  },
  "mixer": { "inserts": [                           // index 0 = Master; all others feed the master
    { "name": "Master", "volume": 0.9, "pan": 0, "mute": false, "solo": false,
      "effects": [ { "type": "limiter", "params": { "ceiling": -0.5 } } ] },
    { "name": "Drums", "volume": 1, "effects": [ { "type": "compressor", "enabled": true, "params": {} } ] }
  ] }
}
```

Rules and conventions:

- `id`s match `[A-Za-z0-9_.-]{1,64}` and must be unique among channels / patterns. Notes refer to
  channels by id; clips refer to patterns by id; `track` and `mixer` are array indices.
- A pattern clip longer than its pattern **loops** the pattern; `offset` shifts where it starts.
  Notes starting at or after the pattern `length` never play.
- Drum channels ignore note length (one-shots); pitch 60 plays the drum at its tuned pitch.
- A channel may have an **arpeggiator**, `"arp"` (omit it for none): every note the channel plays
  becomes a run of notes while it is held, and the notes stay as written (so write the melody, not
  the run). `{ "chord": "minor", "octaves": 2, "rate": 0.25, "direction": "updown", "gate": 0.5,
  "mode": "free" }` — `rate` in beats between run notes (0.25 = 16ths), `gate` each note's length as
  a share of the rate, `direction` up / down / updown / downup / random, `mode` "sort" makes notes
  struck together take turns. Chords: `rosaclef schema` lists them (`octave` = the note itself).
- A channel may be a **layer** of another, `"layerOf": "lead"` (omit it for none): it also plays
  every note written for `lead`, through its own instrument, arpeggiator, volume and mixer insert.
  Use it to thicken a part without copying notes (e.g. an `additive` pad layered with a `granular`
  string texture, a `soundfont` piano with an `fm` electric piano). A layer may have notes of its
  own; a layer cannot be layered on. Deleting a channel means removing its layers' `layerOf`.
- Time-signature changes go in `transport.meters`, sorted by bar (counted from 1):
  `"meters": [ { "bar": 9, "numerator": 3, "denominator": 4 }, { "bar": 17, "numerator": 7, "denominator": 8 } ]`.
  A bar lasts `4 × numerator / denominator` beats (3/4 → 3, 6/8 → 3, 7/8 → 3.5); bars before the
  first change use `beatsPerBar`. Meters only move bar lines: notes and clips stay on their beats.
- Omitted `params`/`options` keys take their defaults (see catalog). Unknown keys are errors.
- Don't reorder `mixer.inserts` or `playlist.tracks` casually — other objects refer to them by index.
- Keep patterns musically self-contained (e.g. a 4-beat drum loop, a 16-beat bassline) and build
  the arrangement from clips; reuse patterns instead of duplicating notes.
- Colors are `#rrggbb`; the studio's palette favours golds, roses, champagne, burgundy, deep jewel tones.

### Automation

`automation` (top level, optional) holds **lanes**: breakpoint curves that move one value over
the arrangement — tempo ramps, filter sweeps, fades. Lanes play in **song mode** (and in
`rosaclef render`); when playback stops or in pattern mode every target returns to its own
value in the project. The producer sees each lane under the playlist tracks.

```jsonc
"automation": [
  { "id": "pad-cutoff", "name": "Pad cutoff", "target": "channel/pad/cutoff", "color": "#8a6bb0",
    "points": [ { "beat": 0, "value": 400 }, { "beat": 32, "value": 6000, "curve": 0.4 } ] }
]
```

- `target` — what the lane drives (one lane per target):

  | target | value (natural units) |
  |---|---|
  | `tempo` | BPM, 20 … 999 |
  | `swing` | 0 … 1 |
  | `channel/<id>/volume` | linear gain 0 … 1.5 |
  | `channel/<id>/pan` | −1 (left) … 1 (right) |
  | `channel/<id>/<param>` | an instrument parameter of that channel, in its catalog unit and range (e.g. `cutoff` in Hz) |
  | `insert/<n>/volume` | mixer insert fader, linear gain 0 … 2 (1 = 0 dB); `insert/0/…` is the master |
  | `insert/<n>/pan` | −1 … 1 |
  | `insert/<n>/effect/<k>/<param>` | parameter of effect `k` (index in that insert's `effects`) |

  Plugin parameters take any number. Integer parameters are rounded while playing.
- `points` — at least one, sorted by `beat` (absolute song time in beats, like clip `start`).
  Before the first point the lane holds the first value, after the last point the last value.
  Two points on the same beat make an instant jump.
- `curve` (optional, −1 … 1, default 0 = straight) shapes the segment that **ends** at that point:
  `> 0` changes slowly first and fast at the end (a sweep that "opens up" late — good for
  filter cutoffs and builds), `< 0` changes fast first and then settles (good for fades).
  The shape is `(e^(6·curve·t) − 1) / (e^(6·curve) − 1)` for t = 0 … 1 across the segment.
- `mute: true` disables a lane; `name` and `color` are cosmetic.
- Tempo automation moves the whole timeline: notes, audio clips, tempo-synced delays and the song's
  duration follow it (`rosaclef render` reports the real duration).
- If you delete a channel or an effect, delete or retarget its lanes too (validation reports
  lanes whose target does not exist).

Examples:

```jsonc
// A 16-bar build that pushes the tempo from 120 to 128 BPM, then holds.
{ "id": "build-tempo", "name": "Build tempo", "target": "tempo",
  "points": [ { "beat": 64, "value": 120 }, { "beat": 128, "value": 128, "curve": 0.3 } ] }
// An 8-bar low-pass sweep on the master filter effect (insert 0, effect 1 is a "filter").
{ "id": "master-sweep", "name": "Riser sweep", "target": "insert/0/effect/1/cutoff",
  "points": [ { "beat": 96, "value": 300 }, { "beat": 128, "value": 18000, "curve": 0.5 } ] }
// Fade the master out over the last 8 bars.
{ "id": "fade-out", "name": "Fade out", "target": "insert/0/volume",
  "points": [ { "beat": 224, "value": 1 }, { "beat": 256, "value": 0, "curve": -0.4 } ] }
```

### Repeats (`repeats`)

The playlist is the written score; `repeats` (top level, optional) are its repeat signs. The
song plays a passage again — `times` times in all — before going on, and **endings** (voltas,
"1." and "2.") play only on some passes. Playing, renders and the Score view all follow them.

```jsonc
"repeats": [
  // Bars 9–16 twice; bar 16 is the 1st ending, bar 17 (after the repeat) the 2nd.
  { "start": 32, "end": 64, "times": 2,
    "endings": [ { "start": 60, "end": 64, "passes": [1] },
                 { "start": 64, "end": 68, "passes": [2] } ] },
  // A four-bar vamp played four times.
  { "start": 96, "end": 112, "times": 4 }
]
```

- `start` / `end` are song beats (put them on bar lines); playing jumps from `end` back to
  `start` until the last pass, which goes on past `end`.
- An ending inside the passage is skipped on the passes it does not list; the last pass's
  ending is written right after `end`. Repeats must not overlap.
- Automation, audio clips and the metronome follow the written position, so they repeat too.
- To "play the chorus twice" or "loop this four times", add a repeat instead of copying clips.

### Sheet music (`score`)

The studio's **Score** view writes the song (or one playlist track, or one pattern) as sheet
music: one staff per channel, measures from the meters, notes quantized for reading. The
optional top-level `score` object says how it reads; it changes nothing that plays.

```jsonc
"score": {
  "key": "Eb",                       // key signature: "auto" (default, guessed), "C", "F#", "Bb", "Am", "C#m", ...
  "hidden": ["hats"],                // channels whose staves are hidden
  "hiddenTracks": [5],               // playlist tracks left out of the song's score
  "clefs": { "keys": "grand", "bass": "bass" },  // auto, treble, treble8vb, bass, alto, grand, percussion
  "marks": [                         // colored passages
    { "start": 32, "end": 64, "color": "#c97b84", "label": "Chorus" },
    { "pattern": "lead", "start": 4, "end": 8, "color": "#3f8f7a", "label": "Motif", "channels": ["lead"] }
  ]
}
```

- A mark's `start` / `end` are song beats, or, with `pattern`, beats of that pattern — the
  passage is then colored wherever the pattern plays. `channels` limits it to some staves.
- When the producer asks to "highlight", "color" or "label" a passage, add a mark; to show or
  hide an instrument in the score, edit `hidden`.

### The film (`animation`)

The Score view's **Film** mode plays the song as a film: the score's pages lie on a desk and a
camera in 3D space above them follows the music — zooming in on a part, pulling back to the
whole band, leaning (`tilt`) and turning (`turn`) so the music runs diagonally across the
picture. The producer can export it as an MP4. The optional top-level `animation` object directs
it; it changes nothing that plays.

```jsonc
"animation": {
  "mode": "manual",                 // "auto" (default): the camera directs itself; "manual": it films `shots`,
                                    //   and directs itself wherever no shot covers the song
  "surface": "walnut",              // the desk: walnut, oak, slate, felt, marble
  "energy": 0.6,                    // auto: 0 calm, the full score held long … 1 restless, more close follows
  "effects": [{ "type": "vignette", "amount": 0.6 }],   // vignette, spotlight, glow
  "shots": [
    { "start": 0, "end": 8, "frame": "desk", "label": "Opening" },
    { "start": 8, "end": 24, "focus": ["drums", "bass"], "frame": "medium", "tilt": 30, "turn": -18,
      "transition": "swoop", "glide": 4, "label": "Groove" },
    { "start": 24, "end": 40, "role": "lead", "frame": "close", "tilt": 40, "turn": 22,
      "to": { "zoom": 1.4, "turn": 10 }, "effects": [{ "type": "spotlight", "amount": 0.7 }], "label": "Melody" },
    { "start": 40, "end": 44, "frame": "detail", "at": 41, "transition": "cut" },
    { "start": 120, "end": 128, "frame": "page", "to": { "zoom": 0.7 }, "label": "Curtain" }
  ]
}
```

- A shot covers `start`–`end` (song beats; put them on bar lines). Where shots overlap, the later
  one is filmed; in manual mode the gaps are filmed by the director.
- **What**: `focus` (channel ids whose staves are framed), or `role` — `lead` (the main melody,
  found by the camera), `rhythm` (drums and bass), `background` (chords, pads), `all`.
- **How much** (`frame`): `desk` (every page), `page`, `system` (the whole line), `medium` (~2
  bars), `close` (~1 bar, the default), `detail` (~a beat: a note or chord filling the picture, the ink up close). `zoom` multiplies it (2 = twice as
  close). Following frames track the playhead along the line and glide to the next line as it ends;
  `at` (a beat) holds the camera on one place instead.
- **Angle**: `tilt` 0–75° (default by frame: the closer, the more), `turn` −180–180° (diagonals:
  ±10–35° reads well), `offset` [x, y] moves the camera by fractions of the picture.
- **Movement**: `to` gives `zoom`, `tilt`, `turn` or `offset` at the shot's end — a slow push in
  (`"to": {"zoom": 1.3}`), a pull back, a turn. **Coming in**: `transition` `glide` (default),
  `cut`, `swoop` (rises away from the desk and comes down), `whip` (fast); `glide` is the
  move's length in beats (default up to a bar), `ease` `smooth`, `linear`, `in`, `out`, `snap`.
- **Effects** (each `{ "type", "amount": 0..1 }`, 0 turns one off): `vignette` (0.5),
  `spotlight` (0; a pool of light on the framed staves), `glow`
  (1; the notes playing light up, their ink glowing warm). A shot's effects override the film's by type.
- Directing well: change shots with the music's sections (8 or 16 bars), frame the part that
  carries each moment (an entry, a solo, a part playing alone), alternate close and wide shots,
  alternate the sign of `turn`, and save `swoop` and `cut` for big moments. To start from what the
  camera would do on its own, the producer can press **Write the director's shots** (it fills
  `shots` from auto mode), then you refine them.

### Drums (`drums`)

For a drum track, prefer the drum part over writing drum notes by hand: it plays a groove from
a library the way a session drummer would — groove A in verses, the bigger groove B in
choruses, fills into the next section, a crash on its first downbeat, a turnaround every 4th
bar and a human feel. The optional top-level `drums` object describes it; `rosaclef drums`
(or **Write drums** in the studio's Drums tab) turns it into ordinary patterns (ids `drums-…`)
and clips on a Drums track, replacing what the last write made.

```jsonc
"drums": {
  "groove": "rock-8ths",            // `rosaclef grooves` lists them (style, meter, tempo range, kit)
  "kit": "Standard Kit",            // optional: a General MIDI drum kit, or "Ebony" (drum machine channels)
  "feel": "natural",                // tight | natural | loose
  "swing": 0,                       // 0..1, straight grooves
  "start": 1,                       // bar the first section starts on
  "ending": "hit",                  // hit (crash + kick after the last section) | none
  "sections": [
    { "name": "Intro",  "bars": 1, "play": "count" },                  // count-in on the side stick
    { "name": "Verse",  "bars": 8, "play": "a", "fill": "beat" },      // fill: none | beat | half | bar
    { "name": "Chorus", "bars": 8, "play": "b", "fill": "bar", "crash": true },
    { "name": "Bridge", "bars": 8, "play": "a", "groove": "rock-halftime", "crash": true },
    { "name": "Stops",  "bars": 2, "play": "hits" }                    // crash + kick on each downbeat; "rest": silence
  ]
}
```

- Edit the part, then run `rosaclef drums`; `--guess` re-derives `start` and `sections` from the
  playlist.
- Drum patterns it wrote may be edited like any pattern (by you or the producer): writing again
  keeps an edited pattern note for note (in `drums.kept`, by drum role, so it follows a kit
  change), and an edit to a groove's plain pattern also changes that groove for the song
  (`drums.grooves`), so its crash, fill and turnaround bars follow. To change a groove for the
  whole song, edit its rows in `drums.grooves` (`"rock-8ths": {"a": [["kick", "X... .... X.X. ...."], ...], "b": [...]}`);
  to give a pattern back to the drummer, remove its entry from `drums.kept`;
  `rosaclef drums --reset-edits` forgets all of them.
- Sections follow each other bar by bar from `start`; a groove only plays in its own meter.
- `written` is managed by Rosaclef; leave it alone.

A single drum pattern can also be made from a groove on its own (the Drums tab works this
way: it always edits one pattern, the one at the song cursor). Its recipe is the pattern's
`drums` object; `rosaclef drums --pattern ID` makes its notes again from it, as many bars as the
pattern is long (on the kit's channels, made if needed). Place it with clips like any pattern.

```jsonc
{ "id": "drums-verse", "name": "Drums · Verse", "length": 16, "notes": [],
  "drums": { "groove": "rock-8ths", "play": "a",   // a | b | hits | count | rest
             "fill": "beat", "crash": true,         // a fill at its end, a crash on its 1
             "turnaround": false, "kit": "Standard Kit", "feel": "natural", "swing": 0, "seed": 1 } }
```

- Change the recipe, then run `rosaclef drums --pattern drums-verse`; `edited: true` means the
  notes were changed by hand since (making it again replaces them).
- Bars where a clip of such a pattern plays are left to it: `rosaclef drums` (the part) writes
  nothing there.

## Musical craft

- Think like a producer: groove (velocity variation, swing), voice-leading in chords,
  frequency space (bass below ~200 Hz, pads filtered, hats high-passed), and arrangement
  energy (intro → build → drop → break → outro, changes every 8 or 16 bars).
- Check your work: `rosaclef mixcheck --text` (or `rosaclef render`, which reports peak/RMS). A
  healthy master peaks around −1 dBTP with the limiter reducing a few dB at most; streaming plays
  everything at about −14 LUFS, so loudness beyond that only costs dynamics.
- Prefer editing parameters over adding effects; keep one `limiter` last on the master.
- Pick each part's instrument from **Choosing an instrument** (in the catalog below), start from
  one of its presets (`rosaclef presets NAME` prints the instrument JSON), then adjust params.
  Every option value and parameter is documented in the catalog; layer two channels playing the
  same notes for a bigger sound.

## Factory presets

Starting points for sound design. `rosaclef presets NAME` prints a preset as the
exact `instrument` JSON to paste into a channel (then tweak its params);
`rosaclef presets TYPE` lists the presets of one engine.

{{PRESETS}}

## Device catalog

{{CATALOG}}
"##;
