//! Agent guide files written into every project folder.
//!
//! `AGENTS.md` is the canonical guide (read by Codex, OpenCode, Aider, ...).
//! `CLAUDE.md` and `GEMINI.md` import it so Claude Code and Gemini CLI pick
//! it up automatically. Files that the user has edited (no generated marker)
//! are left alone.

use crate::folder::Folder;
use anyhow::Result;

const MARKER: &str = "<!-- rosaclef:generated";

/// Write the guides into `folder`. `exe` is how the `rosaclef` command is
/// reached (the path of the executable, or just `rosaclef`).
pub fn write(folder: &Folder, exe: &str) -> Result<()> {
    let body = agents_md(exe);
    put(folder, "AGENTS.md", &body)?;
    let pointer = format!(
        "{MARKER} — regenerated by the studio; delete this line to keep your own edits -->\n\
         # Rosaclef project\n\n\
         This folder is a Rosaclef music project. Read and follow AGENTS.md:\n\n@AGENTS.md\n"
    );
    put(folder, "CLAUDE.md", &pointer)?;
    put(folder, "GEMINI.md", &pointer)?;
    Ok(())
}

fn put(folder: &Folder, name: &str, text: &str) -> Result<()> {
    let path = folder.dir.join(name);
    if let Ok(existing) = folder.fs.read_to_string(&path) {
        if !existing.starts_with(MARKER) {
            return Ok(()); // user-owned
        }
    }
    Ok(folder.fs.write_if_changed(&path, text)?)
}

pub fn agents_md(exe: &str) -> String {
    let catalog = rosaclef_core::catalog_markdown();
    GUIDE
        .replace("{{EXE}}", exe)
        .replace("{{CATALOG}}", &catalog)
        .replace("{{PRESETS}}", &rosaclef_core::presets_markdown())
        .replace("{{MARKER}}", MARKER)
}

const GUIDE: &str = r##"{{MARKER}} — regenerated by the studio; delete this line to keep your own edits -->
# Rosaclef project — guide for coding agents

You are working inside a **Rosaclef** music project, next to a human producer who
has the Rosaclef studio (an FL Studio–style DAW) open in their browser. You are the
studio's resident assistant: you compose, arrange, sound-design and mix by editing
the project data. **The studio watches the files in this folder and updates live** —
the producer sees and hears every change you save within a fraction of a second.

## Files

| path | what |
|---|---|
| `project.json` | **The song.** Everything: tempo, instruments, patterns, arrangement, mixer. Edit this. |
| `project.schema.json` | JSON Schema (draft 2020-12) for `project.json`. |
| `.rosaclef/context.json` | What the producer is doing *right now* (see "The producer's context" below). Schema: `.rosaclef/context.schema.json`. |
| `.rosaclef/status.json` | Result of the studio's last load of `project.json` (`ok` + `issues`). Check it after every edit. |
| `samples/` | Audio files (wav/flac/mp3/ogg) used by `sampler` instruments and audio clips. |
| `renders/` | Exported mixdowns. |

## The producer's context

The studio continuously rewrites `.rosaclef/context.json` (read-only for you)
with what the producer is doing. **Read it whenever they say "this", "here",
"these notes", "the selected…", "what I just did", or refer to a part of the
song without naming it.** Fields (full schema in `.rosaclef/context.schema.json`):

- `focus` — panel they last touched: `playlist`, `score`, `channel rack`, `piano roll`, `voice to notes`, `mixer`, `browser`, `agent`.
- `transport` — `playing`, `mode` (`song` / `pattern`), playhead `positionBeats` and `position` (`bar:beat:tick`), `bpm`.
- `selection` — the selected `pattern`, `channel`, mixer `insert` and playlist `track`; `notes`
  (selected notes of the selected pattern, each with its `index` in that pattern's `notes`) and
  `clips` (selected clips with their `index` in `playlist.clips`), and `automation` (the selected
  automation lane — `index` in `automation`, `id`, `target`, selected `points` with their index,
  `valueAtPlayhead` — or null).
- `visible` — what is on screen: the playlist's beat range and tracks, and (when the piano roll is
  open) its pattern, channel, beat range and pitch range. "This part" usually means this range.
- `recentEdits` — the producer's latest manual edits in plain words, newest last
  (e.g. `pattern "groove": +1 note on "snare" (D3 at beat 2.5)`, `channel "bass": cutoff 1200 → 900`).
  Your own edits to `project.json` are not listed.
- `seq` / `updatedAt` — increase on every write; compare them to know whether it changed.

Example:

```json
{
  "seq": 41, "updatedAt": "2026-09-29T21:14:03Z",
  "focus": "piano roll", "dock": "piano roll",
  "transport": { "playing": false, "mode": "pattern", "positionBeats": 2, "position": "001:03:00", "bpm": 92 },
  "selection": {
    "pattern": { "id": "keys", "name": "Keys", "length": 16, "noteCount": 80 },
    "channel": { "id": "keys", "name": "Rhodes", "instrument": "sextant", "mixer": 4 },
    "insert": { "index": 4, "name": "Keys" }, "track": { "index": 2, "name": "Keys" },
    "notes": [ { "index": 12, "note": { "channel": "keys", "pitch": 63, "start": 2.5, "length": 1, "velocity": 0.72 } } ],
    "clips": []
  },
  "visible": {
    "playlist": { "startBeat": 0, "endBeat": 37, "firstTrack": 0, "lastTrack": 7 },
    "pianoRoll": { "pattern": "keys", "channel": "keys", "startBeat": 0, "endBeat": 11.3, "lowPitch": 55, "highPitch": 74 }
  },
  "recentEdits": [ { "at": "2026-09-29T21:13:58Z", "summary": "pattern \"keys\": edited 1 note (C4 at beat 2.5 → D♯4 at beat 2.5)" } ]
}
```

Indexes refer to `project.json` as it was when the context was written; re-read the project before
editing, and prefer matching notes by their content if the project changed since.

## Workflow

1. Read `.rosaclef/context.json` (what the producer is doing) and `project.json`
   (or run `rosaclef summary` for an overview).
2. Edit `project.json` directly — small, targeted edits. Keep the file's formatting style
   (one note per line); the studio rewrites it canonically on its next save anyway.
3. Validate: `rosaclef validate` (exit status 0 = ok). Errors name the exact JSON path, e.g.
   `patterns[2].notes[14].pitch: value 130 is outside the allowed range 0..127`.
   If the file is invalid the studio keeps playing the last good version and shows
   the producer the errors, so fix them promptly.
4. Tell the producer briefly what you changed (they can undo any change in the studio with Ctrl+Z).

The producer may be editing in the UI at the same time. Always re-read `project.json`
right before editing it, and never rewrite the whole file from memory.

### Command line tools

`rosaclef` is on your PATH (`{{EXE}}`):

- `rosaclef validate` — check `project.json`.
- `rosaclef summary` — compact overview of channels, patterns, arrangement and mixer.
- `rosaclef catalog` — every instrument/effect and its parameters (also below).
- `rosaclef presets [TYPE|NAME]` — factory presets; with a name, prints the instrument JSON.
- `rosaclef render [--pattern ID --loops N] [--out renders/x.wav]` — offline mixdown to WAV
  (prints duration, peak and RMS — useful to check levels without listening).
- `rosaclef note --channel ID --pitch 60 --seconds 2 --out samples/x.wav` — synthesize one note
  of a channel's instrument (or `--instrument '{"type":"drum","options":{"kind":"clap"}}'`) into a sample.
- You may also create samples any other way (e.g. write a WAV with Python) into `samples/`.
- `rosaclef import-midi FILE.mid --name NAME --library ..` / `rosaclef import-lmms FILE.mmpz ...` —
  turn a MIDI file or an LMMS project into a new project next to this one (prints what was approximated).
  To add a MIDI file's parts to *this* song instead: `curl -X POST --data-binary @FILE.mid "$ROSACLEF_URL/api/import-midi?into=current"`.

HTTP API (while the studio runs, base URL in `$ROSACLEF_URL`): `GET /api/project`,
`PUT /api/project` (full document; validated), `GET /api/schema`, `GET /api/catalog`,
`GET /api/projects` (the library), `GET /api/files` (this project's files).
Editing the file is preferred. The producer can open another project from the studio; when
that happens your terminal session is restarted in the new project's folder.

## Data model

All **times are in beats** (quarter notes): `start: 4` is the downbeat of bar 2 in 4/4,
`0.25` is a 16th note, `0.5` an 8th, `1` a quarter. **Pitches are MIDI numbers**:
60 = C4 (middle C), 61 = C#4, 69 = A4; +12 = one octave up.
Velocities, volumes and most mix values are 0..1 (volumes are linear gain, 1.0 = 0 dB).

```jsonc
{
  "$schema": "./project.schema.json",
  "format": "rosaclef/1",
  "meta": { "title": "Velvet Hour", "author": "", "description": "" },
  "transport": { "bpm": 118, "beatsPerBar": 4, "swing": 0.12 },   // swing: 0 straight .. 1 triplet (16ths); optional "transpose": -12..12 semitones
  "channels": [                                     // the channel rack: one instrument each
    { "id": "kick", "name": "Kick", "color": "#d4af37",
      "instrument": { "type": "drum", "params": { "tone": 0.35 }, "options": { "kind": "kick" } },
      "volume": 0.9, "pan": 0, "mute": false, "mixer": 1 }  // mixer = insert index
  ],
  "patterns": [                                     // notes for any number of channels
    { "id": "groove", "name": "Groove", "color": "#d4af37", "length": 4,
      "notes": [
        { "channel": "kick", "pitch": 60, "start": 0, "length": 0.25, "velocity": 0.95 },
        { "channel": "kick", "pitch": 60, "start": 1, "length": 0.25, "velocity": 0.95 }
      ] }
  ],
  "playlist": {                                     // the arrangement
    "tracks": [ { "name": "Drums", "mute": false } ],
    "clips": [
      { "pattern": "groove", "track": 0, "start": 0, "length": 32 },           // pattern clip (loops the pattern)
      { "sample": "samples/vox.wav", "track": 1, "start": 16, "length": 8,     // audio clip
        "offset": 0, "gain": 1, "mixer": 7 }
    ]
  },
  "mixer": { "inserts": [                           // index 0 = Master; all others feed the master
    { "name": "Master", "volume": 0.9, "pan": 0, "mute": false, "solo": false,
      "effects": [ { "type": "limiter", "params": { "ceiling": -0.5 } } ] },
    { "name": "Drums", "volume": 1, "effects": [ { "type": "compressor", "enabled": true, "params": {} } ] }
  ] }
}
```

Rules and conventions:

- `id`s match `[A-Za-z0-9_.-]{1,64}` and must be unique among channels / patterns. Notes refer to
  channels by id; clips refer to patterns by id; `track` and `mixer` are array indices.
- A pattern clip longer than its pattern **loops** the pattern; `offset` shifts where it starts.
  Notes starting at or after the pattern `length` never play.
- Drum channels ignore note length (one-shots); pitch 60 plays the drum at its tuned pitch.
- A channel may have an **arpeggiator**, `"arp"` (omit it for none): every note the channel plays
  becomes a run of notes while it is held, and the notes stay as written (so write the melody, not
  the run). `{ "chord": "minor", "octaves": 2, "rate": 0.25, "direction": "updown", "gate": 0.5,
  "mode": "free" }` — `rate` in beats between run notes (0.25 = 16ths), `gate` each note's length as
  a share of the rate, `direction` up / down / updown / downup / random, `mode` "sort" makes notes
  struck together take turns. Chords: `rosaclef schema` lists them (`octave` = the note itself).
- Time-signature changes go in `transport.meters`, sorted by bar (counted from 1):
  `"meters": [ { "bar": 9, "numerator": 3, "denominator": 4 }, { "bar": 17, "numerator": 7, "denominator": 8 } ]`.
  A bar lasts `4 × numerator / denominator` beats (3/4 → 3, 6/8 → 3, 7/8 → 3.5); bars before the
  first change use `beatsPerBar`. Meters only move bar lines: notes and clips stay on their beats.
- Omitted `params`/`options` keys take their defaults (see catalog). Unknown keys are errors.
- Don't reorder `mixer.inserts` or `playlist.tracks` casually — other objects refer to them by index.
- Keep patterns musically self-contained (e.g. a 4-beat drum loop, a 16-beat bassline) and build
  the arrangement from clips; reuse patterns instead of duplicating notes.
- Colors are `#rrggbb`; the studio's palette favours golds, roses, champagne, burgundy, deep jewel tones.

### Automation

`automation` (top level, optional) holds **lanes**: breakpoint curves that move one value over
the arrangement — tempo ramps, filter sweeps, fades. Lanes play in **song mode** (and in
`rosaclef render`); when playback stops or in pattern mode every target returns to its own
value in the project. The producer sees each lane under the playlist tracks.

```jsonc
"automation": [
  { "id": "pad-cutoff", "name": "Pad cutoff", "target": "channel/pad/cutoff", "color": "#8a6bb0",
    "points": [ { "beat": 0, "value": 400 }, { "beat": 32, "value": 6000, "curve": 0.4 } ] }
]
```

- `target` — what the lane drives (one lane per target):

  | target | value (natural units) |
  |---|---|
  | `tempo` | BPM, 20 … 999 |
  | `swing` | 0 … 1 |
  | `channel/<id>/volume` | linear gain 0 … 1.5 |
  | `channel/<id>/pan` | −1 (left) … 1 (right) |
  | `channel/<id>/<param>` | an instrument parameter of that channel, in its catalog unit and range (e.g. `cutoff` in Hz) |
  | `insert/<n>/volume` | mixer insert fader, linear gain 0 … 2 (1 = 0 dB); `insert/0/…` is the master |
  | `insert/<n>/pan` | −1 … 1 |
  | `insert/<n>/effect/<k>/<param>` | parameter of effect `k` (index in that insert's `effects`) |

  Plugin parameters take any number. Integer parameters are rounded while playing.
- `points` — at least one, sorted by `beat` (absolute song time in beats, like clip `start`).
  Before the first point the lane holds the first value, after the last point the last value.
  Two points on the same beat make an instant jump.
- `curve` (optional, −1 … 1, default 0 = straight) shapes the segment that **ends** at that point:
  `> 0` changes slowly first and fast at the end (a sweep that "opens up" late — good for
  filter cutoffs and builds), `< 0` changes fast first and then settles (good for fades).
  The shape is `(e^(6·curve·t) − 1) / (e^(6·curve) − 1)` for t = 0 … 1 across the segment.
- `mute: true` disables a lane; `name` and `color` are cosmetic.
- Tempo automation moves the whole timeline: notes, audio clips, tempo-synced delays and the song's
  duration follow it (`rosaclef render` reports the real duration).
- If you delete a channel or an effect, delete or retarget its lanes too (validation reports
  lanes whose target does not exist).

Examples:

```jsonc
// A 16-bar build that pushes the tempo from 120 to 128 BPM, then holds.
{ "id": "build-tempo", "name": "Build tempo", "target": "tempo",
  "points": [ { "beat": 64, "value": 120 }, { "beat": 128, "value": 128, "curve": 0.3 } ] }
// An 8-bar low-pass sweep on the master filter effect (insert 0, effect 1 is a "filter").
{ "id": "master-sweep", "name": "Riser sweep", "target": "insert/0/effect/1/cutoff",
  "points": [ { "beat": 96, "value": 300 }, { "beat": 128, "value": 18000, "curve": 0.5 } ] }
// Fade the master out over the last 8 bars.
{ "id": "fade-out", "name": "Fade out", "target": "insert/0/volume",
  "points": [ { "beat": 224, "value": 1 }, { "beat": 256, "value": 0, "curve": -0.4 } ] }
```

### Repeats (`repeats`)

The playlist is the written score; `repeats` (top level, optional) are its repeat signs. The
song plays a passage again — `times` times in all — before going on, and **endings** (voltas,
"1." and "2.") play only on some passes. Playing, renders and the Score view all follow them.

```jsonc
"repeats": [
  // Bars 9–16 twice; bar 16 is the 1st ending, bar 17 (after the repeat) the 2nd.
  { "start": 32, "end": 64, "times": 2,
    "endings": [ { "start": 60, "end": 64, "passes": [1] },
                 { "start": 64, "end": 68, "passes": [2] } ] },
  // A four-bar vamp played four times.
  { "start": 96, "end": 112, "times": 4 }
]
```

- `start` / `end` are song beats (put them on bar lines); playing jumps from `end` back to
  `start` until the last pass, which goes on past `end`.
- An ending inside the passage is skipped on the passes it does not list; the last pass's
  ending is written right after `end`. Repeats must not overlap.
- Automation, audio clips and the metronome follow the written position, so they repeat too.
- To "play the chorus twice" or "loop this four times", add a repeat instead of copying clips.

### Sheet music (`score`)

The studio's **Score** view writes the song (or one playlist track, or one pattern) as sheet
music: one staff per channel, measures from the meters, notes quantized for reading. The
optional top-level `score` object says how it reads; it changes nothing that plays.

```jsonc
"score": {
  "key": "Eb",                       // key signature: "auto" (default, guessed), "C", "F#", "Bb", "Am", "C#m", ...
  "hidden": ["hats"],                // channels whose staves are hidden
  "hiddenTracks": [5],               // playlist tracks left out of the song's score
  "clefs": { "keys": "grand", "bass": "bass" },  // auto, treble, treble8vb, bass, alto, grand, percussion
  "marks": [                         // colored passages
    { "start": 32, "end": 64, "color": "#c97b84", "label": "Chorus" },
    { "pattern": "lead", "start": 4, "end": 8, "color": "#3f8f7a", "label": "Motif", "channels": ["lead"] }
  ]
}
```

- A mark's `start` / `end` are song beats, or, with `pattern`, beats of that pattern — the
  passage is then colored wherever the pattern plays. `channels` limits it to some staves.
- When the producer asks to "highlight", "color" or "label" a passage, add a mark; to show or
  hide an instrument in the score, edit `hidden`.

### Reuse by reference (`uses`)

A pattern can play other patterns — or ranges of them — **by reference**, instead of copying
their notes. Editing the used pattern changes every place that uses it.

```jsonc
{ "id": "verse", "name": "Verse", "length": 16,
  "notes": [ /* its own notes */ ],
  "uses": [
    { "pattern": "hook", "start": 4, "transpose": 5 },              // the hook a fourth up, at beat 4
    { "pattern": "hook", "from": 2, "to": 4, "start": 12,           // beats 2–4 of the hook ...
      "channel": "bass", "transpose": -12, "velocity": 0.7 }        // ... doubled by the bass
  ] }
```

- `start`: where it starts in this pattern; `from` / `to`: the range of the used pattern (default:
  all of it; notes are cut at `to`); `transpose`: semitones (drum channels are not moved);
  `channel`: play every note on this channel; `velocity`: a factor; `verse`: the verse its
  lyrics sing.
- Uses nest; a pattern cannot contain itself. `rosaclef summary` shows the sounding notes.
- When a motif, riff or phrase comes back (or is doubled), use it instead of copying notes.
  Copy only when the copy will change.

### Lyrics (`lyrics`)

Words live in the pattern whose notes sing them, one line per vocal channel, with **verses**:

```jsonc
{ "id": "verse", "name": "Verse", "length": 16, "notes": [ /* the melody, on "lead" */ ],
  "lyrics": [
    { "channel": "lead", "lang": "en",
      "verses": {
        "1": "Hel-lo dark-ness my old friend _ / I've come to talk with you a-gain",
        "2": "Be-cause a vi-sion soft-ly creep-ing _ / left its seeds while I was sleep-ing"
      } }
  ] }
```

- Each token takes one note of the channel, in time order: a space ends a word, `-` splits a
  word into syllables (`Hel-lo`), `_` holds the previous syllable over a note (a melisma),
  `/` ends a line and `//` a paragraph, `word[w ɜ d]` gives a pronunciation in IPA, `(br)` is a
  breath; `\` escapes a character (`\-`). Validation warns when a verse has more syllables than
  notes or the reverse — add `_` or notes until they match.
- Which verse plays: a use's `verse`, else the clip's `"verse": 2`, else the pass of the repeat
  it plays in (pass 2 sings verse 2), else 1. A line without that verse sings its first one, so
  a chorus is written once.
- A used pattern brings its own words; a line gives words to the notes its uses did not. Notes a
  use moves to another `channel` (a doubling) leave their words behind.
- `mode`: `sing` (default), `rap` (rhythm only) or `speak`. One voice sings one note at a time,
  so keep a sung channel monophonic.
- Fixed phoneme timing (from aligning a recording) is kept in `timing`; leave it alone unless asked.

**Exports.** `rosaclef export --format ID [--pattern ID --verse N] [--out FILE]` writes the song
(or one pattern) as `midi` (lyric events), `musicxml`, `ustx` (OpenUtau), `svp` (Synthesizer V),
`ds` (DiffSinger), `ultrastar`, `lrc`, `ttml`, `jam` (timed words), `tagged` (`[Verse]` /
`[Chorus]` text for song generators) or `ssml`; `rosaclef export --list` describes them and
`--out -` prints the file. Name patterns after song sections ("Verse", "Chorus") so tagged lyrics
are labeled. `rosaclef align --pattern ID --channel ID --at SECONDS take.TextGrid` (or WhisperX
`.json`) fills `timing` from a recording a forced aligner has read.

## Musical craft

- Think like a producer: groove (velocity variation, swing), voice-leading in chords,
  frequency space (bass below ~200 Hz, pads filtered, hats high-passed), and arrangement
  energy (intro → build → drop → break → outro, changes every 8 or 16 bars).
- Check your work: `rosaclef render` reports peak/RMS. A healthy master peaks around −1 to
  −0.3 dBFS with the limiter; an RMS far below −20 dBFS usually means something is too quiet.
- Prefer editing parameters over adding effects; keep one `limiter` last on the master.

## Factory presets

Starting points for sound design. `rosaclef presets NAME` prints a preset as the
exact `instrument` JSON to paste into a channel (then tweak its params);
`rosaclef presets TYPE` lists the presets of one engine.

{{PRESETS}}

## Device catalog

{{CATALOG}}
"##;
