"""Generate web/src/smufl.js: the Bravura glyphs the Score view draws.

The score draws glyphs with the Bravura font itself (web/fonts/Bravura.woff2,
SIL Open Font License); this table gives each glyph's character and its ink
box in staff spaces, for layout, and its outline (an SVG path in staff
spaces, y down from the origin) for the PDF export, which draws the glyphs
as shapes rather than embedding the font. Bravura's own metadata JSON would
give the same boxes; they are measured from the outlines so the font is the
only input.

    pip install fonttools
    python3 tools/gen_smufl.py Bravura.otf glyphnames.json > web/src/smufl.js
    (cd web && npx --yes prettier@3.8.1 --write src/smufl.js)

Bravura: https://github.com/steinbergmedia/bravura (redist/otf/Bravura.otf).
glyphnames.json: https://github.com/w3c/smufl (metadata/glyphnames.json).
"""

import json
import sys

import re

from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont

GLYPHS = [
    "gClef",
    "gClef8vb",
    "fClef",
    "cClef",
    "unpitchedPercussionClef1",
    "noteheadWhole",
    "noteheadHalf",
    "noteheadBlack",
    "noteheadXWhole",
    "noteheadXHalf",
    "noteheadXBlack",
    "noteheadCircleX",
    "flag8thUp",
    "flag8thDown",
    "flag16thUp",
    "flag16thDown",
    "flag32ndUp",
    "flag32ndDown",
    "restWhole",
    "restHalf",
    "restQuarter",
    "rest8th",
    "rest16th",
    "rest32nd",
    "accidentalFlat",
    "accidentalNatural",
    "accidentalSharp",
    "accidentalDoubleSharp",
    "accidentalDoubleFlat",
    "augmentationDot",
    "timeSig0",
    "timeSig1",
    "timeSig2",
    "timeSig3",
    "timeSig4",
    "timeSig5",
    "timeSig6",
    "timeSig7",
    "timeSig8",
    "timeSig9",
    "timeSigCommon",
    "timeSigCutCommon",
    "brace",
    "bracketTop",
    "bracketBottom",
    "metNoteQuarterUp",
    "tuplet3",
    "repeatDot",
]


def num(v):
    """A number as Prettier writes it (no trailing zeros)."""
    s = f"{round(v, 3) + 0.0:.3f}".rstrip("0").rstrip(".")
    return "0" if s in ("0", "-0") else s


def outline(gs, name, sp):
    """The glyph's outline as SVG path data in staff spaces, y down."""
    pen = SVGPathPen(gs)
    gs[name].draw(TransformPen(pen, (1 / sp, 0, 0, -1 / sp, 0, 0)))
    return re.sub(r"-?\d+\.?\d*(?:e-?\d+)?", lambda m: num(float(m.group(0))), pen.getCommands())


def main():
    font = TTFont(sys.argv[1])
    names = json.load(open(sys.argv[2]))
    cmap = font.getBestCmap()
    gs = font.getGlyphSet()
    upm = font["head"].unitsPerEm
    sp = upm / 4  # one staff space is a quarter of the em
    print("// Generated by tools/gen_smufl.py from Bravura (SIL Open Font License) — do not edit.")
    print("// Each glyph: its character in the font, its ink box in staff spaces (y down")
    print("// from the glyph's origin, the baseline, at a staff line) and its outline.")
    print()
    print("/** type Glyph = { c: String, x0: Number, x1: Number, top: Number, bottom: Number, d: String } */")
    print()
    print("/** const G: {")
    print(",\n".join(f"    {n}: Glyph" for n in GLYPHS))
    print("} */")
    print("export const G = {")
    for n in GLYPHS:
        cp = int(names[n]["codepoint"][2:], 16)
        pen = BoundsPen(gs)
        gs[cmap[cp]].draw(pen)
        x0, y0, x1, y1 = pen.bounds
        box = ", ".join(f"{k}: {num(v / sp)}" for k, v in (("x0", x0), ("x1", x1), ("top", -y1), ("bottom", -y0)))
        d = outline(gs, cmap[cp], sp)
        print(f'  {n}: {{ c: "\\u{{{cp:x}}}", {box}, d: "{d}" }},')
    print("};")
    print()
    print("/** Every glyph, for looking one up by its character. */")
    print("/** const GLYPHS: Glyph[] */")
    print("export const GLYPHS = [" + ", ".join(f"G.{n}" for n in GLYPHS) + "];")


if __name__ == "__main__":
    main()
