"""Generate web/src/smufl.js: the Bravura glyphs the Score view draws.

The score draws glyphs with the Bravura font itself (web/fonts/Bravura.woff2,
SIL Open Font License); this table gives each glyph's character and its ink
box in staff spaces, for layout. Bravura's own metadata JSON would give the
same boxes; they are measured from the outlines so the font is the only input.

    pip install fonttools
    python3 tools/gen_smufl.py Bravura.otf glyphnames.json > web/src/smufl.js

Bravura: https://github.com/steinbergmedia/bravura (redist/otf/Bravura.otf).
glyphnames.json: https://github.com/w3c/smufl (metadata/glyphnames.json).
"""

import json
import sys

from fontTools.pens.boundsPen import BoundsPen
from fontTools.ttLib import TTFont

GLYPHS = [
    "gClef",
    "gClef8vb",
    "fClef",
    "cClef",
    "unpitchedPercussionClef1",
    "noteheadWhole",
    "noteheadHalf",
    "noteheadBlack",
    "noteheadXWhole",
    "noteheadXHalf",
    "noteheadXBlack",
    "noteheadCircleX",
    "flag8thUp",
    "flag8thDown",
    "flag16thUp",
    "flag16thDown",
    "flag32ndUp",
    "flag32ndDown",
    "restWhole",
    "restHalf",
    "restQuarter",
    "rest8th",
    "rest16th",
    "rest32nd",
    "accidentalFlat",
    "accidentalNatural",
    "accidentalSharp",
    "accidentalDoubleSharp",
    "accidentalDoubleFlat",
    "augmentationDot",
    "timeSig0",
    "timeSig1",
    "timeSig2",
    "timeSig3",
    "timeSig4",
    "timeSig5",
    "timeSig6",
    "timeSig7",
    "timeSig8",
    "timeSig9",
    "timeSigCommon",
    "timeSigCutCommon",
    "brace",
    "bracketTop",
    "bracketBottom",
    "metNoteQuarterUp",
    "tuplet3",
    "repeatDot",
]


def num(v):
    """A number as Prettier writes it (no trailing zeros)."""
    v = round(v, 3) + 0.0
    return f"{v:.3f}".rstrip("0").rstrip(".").replace("-0", "0") if v != 0 else "0"


def main():
    font = TTFont(sys.argv[1])
    names = json.load(open(sys.argv[2]))
    cmap = font.getBestCmap()
    gs = font.getGlyphSet()
    upm = font["head"].unitsPerEm
    sp = upm / 4  # one staff space is a quarter of the em
    print("// Generated by tools/gen_smufl.py from Bravura (SIL Open Font License) — do not edit.")
    print("// Each glyph: its character in the font and its ink box in staff spaces,")
    print("// y down from the glyph's origin (the baseline, at a staff line).")
    print()
    print("/** type Glyph = { c: String, x0: Number, x1: Number, top: Number, bottom: Number } */")
    print()
    print("/** const G: {")
    print(",\n".join(f"    {n}: Glyph" for n in GLYPHS))
    print("} */")
    print("export const G = {")
    for n in GLYPHS:
        cp = int(names[n]["codepoint"][2:], 16)
        pen = BoundsPen(gs)
        gs[cmap[cp]].draw(pen)
        x0, y0, x1, y1 = pen.bounds
        box = ", ".join(f"{k}: {num(v / sp)}" for k, v in (("x0", x0), ("x1", x1), ("top", -y1), ("bottom", -y0)))
        print(f'  {n}: {{ c: "\\u{{{cp:x}}}", {box} }},')
    print("};")


if __name__ == "__main__":
    main()
