//! Agent guide files written into every project folder.
//!
//! `AGENTS.md` is the canonical guide (read by Codex, OpenCode, Aider, ...).
//! `CLAUDE.md` and `GEMINI.md` import it so Claude Code and Gemini CLI pick
//! it up automatically. Files that the user has edited (no generated marker)
//! are left alone.

use crate::folder::{write_if_changed, Folder};
use anyhow::Result;

const MARKER: &str = "<!-- rosaclef:generated";

pub fn write(folder: &Folder) -> Result<()> {
    let body = agents_md();
    put(folder, "AGENTS.md", &body)?;
    let pointer = format!(
        "{MARKER} — regenerated by the studio; delete this line to keep your own edits -->\n\
         # Rosaclef project\n\n\
         This folder is a Rosaclef music project. Read and follow AGENTS.md:\n\n@AGENTS.md\n"
    );
    put(folder, "CLAUDE.md", &pointer)?;
    put(folder, "GEMINI.md", &pointer)?;
    Ok(())
}

fn put(folder: &Folder, name: &str, text: &str) -> Result<()> {
    let path = folder.dir.join(name);
    if let Ok(existing) = std::fs::read_to_string(&path) {
        if !existing.starts_with(MARKER) {
            return Ok(()); // user-owned
        }
    }
    write_if_changed(&path, text)
}

pub fn agents_md() -> String {
    let exe = std::env::current_exe().ok().map(|p| p.display().to_string()).unwrap_or_else(|| "rosaclef".into());
    let catalog = rosaclef_core::catalog_markdown();
    GUIDE.replace("{{EXE}}", &exe).replace("{{CATALOG}}", &catalog).replace("{{MARKER}}", MARKER)
}

const GUIDE: &str = r##"{{MARKER}} — regenerated by the studio; delete this line to keep your own edits -->
# Rosaclef project — guide for coding agents

You are working inside a **Rosaclef** music project, next to a human producer who
has the Rosaclef studio (an FL Studio–style DAW) open in their browser. You are the
studio's resident assistant: you compose, arrange, sound-design and mix by editing
the project data. **The studio watches the files in this folder and updates live** —
the producer sees and hears every change you save within a fraction of a second.

## Files

| path | what |
|---|---|
| `project.json` | **The song.** Everything: tempo, instruments, patterns, arrangement, mixer. Edit this. |
| `project.schema.json` | JSON Schema (draft 2020-12) for `project.json`. |
| `.rosaclef/context.json` | What the producer is looking at *right now*: open view, selected pattern/channel/insert, playhead, selected notes. Read it when they say "this", "here", "the selected…". |
| `.rosaclef/status.json` | Result of the studio's last load of `project.json` (`ok` + `issues`). Check it after every edit. |
| `samples/` | Audio files (wav/flac/mp3/ogg) used by `sampler` instruments and audio clips. |
| `renders/` | Exported mixdowns. |

## Workflow

1. Read `.rosaclef/context.json` and `project.json` (or run `rosaclef summary` for an overview).
2. Edit `project.json` directly — small, targeted edits. Keep the file's formatting style
   (one note per line); the studio rewrites it canonically on its next save anyway.
3. Validate: `rosaclef validate` (exit status 0 = ok). Errors name the exact JSON path, e.g.
   `patterns[2].notes[14].pitch: value 130 is outside the allowed range 0..127`.
   If the file is invalid the studio keeps playing the last good version and shows
   the producer the errors, so fix them promptly.
4. Tell the producer briefly what you changed (they can undo any change in the studio with Ctrl+Z).

The producer may be editing in the UI at the same time. Always re-read `project.json`
right before editing it, and never rewrite the whole file from memory.

### Command line tools

`rosaclef` is on your PATH (`{{EXE}}`):

- `rosaclef validate` — check `project.json`.
- `rosaclef summary` — compact overview of channels, patterns, arrangement and mixer.
- `rosaclef catalog` — every instrument/effect and its parameters (also below).
- `rosaclef render [--pattern ID --loops N] [--out renders/x.wav]` — offline mixdown to WAV
  (prints duration, peak and RMS — useful to check levels without listening).
- `rosaclef note --channel ID --pitch 60 --seconds 2 --out samples/x.wav` — synthesize one note
  of a channel's instrument (or `--instrument '{"type":"drum","options":{"kind":"clap"}}'`) into a sample.
- You may also create samples any other way (e.g. write a WAV with Python) into `samples/`.

HTTP API (while the studio runs, base URL in `$ROSACLEF_URL`): `GET /api/project`,
`PUT /api/project` (full document; validated), `GET /api/schema`, `GET /api/catalog`.
Editing the file is preferred.

## Data model

All **times are in beats** (quarter notes): `start: 4` is the downbeat of bar 2 in 4/4,
`0.25` is a 16th note, `0.5` an 8th, `1` a quarter. **Pitches are MIDI numbers**:
60 = C4 (middle C), 61 = C#4, 69 = A4; +12 = one octave up.
Velocities, volumes and most mix values are 0..1 (volumes are linear gain, 1.0 = 0 dB).

```jsonc
{
  "$schema": "./project.schema.json",
  "format": "rosaclef/1",
  "meta": { "title": "Velvet Hour", "author": "", "description": "" },
  "transport": { "bpm": 118, "beatsPerBar": 4, "swing": 0.12 },   // swing: 0 straight .. 1 triplet (16ths)
  "channels": [                                     // the channel rack: one instrument each
    { "id": "kick", "name": "Kick", "color": "#d4af37",
      "instrument": { "type": "drum", "params": { "tone": 0.35 }, "options": { "kind": "kick" } },
      "volume": 0.9, "pan": 0, "mute": false, "mixer": 1 }  // mixer = insert index
  ],
  "patterns": [                                     // notes for any number of channels
    { "id": "groove", "name": "Groove", "color": "#d4af37", "length": 4,
      "notes": [
        { "channel": "kick", "pitch": 60, "start": 0, "length": 0.25, "velocity": 0.95 },
        { "channel": "kick", "pitch": 60, "start": 1, "length": 0.25, "velocity": 0.95 }
      ] }
  ],
  "playlist": {                                     // the arrangement
    "tracks": [ { "name": "Drums", "mute": false } ],
    "clips": [
      { "pattern": "groove", "track": 0, "start": 0, "length": 32 },           // pattern clip (loops the pattern)
      { "sample": "samples/vox.wav", "track": 1, "start": 16, "length": 8,     // audio clip
        "offset": 0, "gain": 1, "mixer": 7 }
    ]
  },
  "mixer": { "inserts": [                           // index 0 = Master; all others feed the master
    { "name": "Master", "volume": 0.9, "pan": 0, "mute": false, "solo": false,
      "effects": [ { "type": "limiter", "params": { "ceiling": -0.5 } } ] },
    { "name": "Drums", "volume": 1, "effects": [ { "type": "compressor", "enabled": true, "params": {} } ] }
  ] }
}
```

Rules and conventions:

- `id`s match `[A-Za-z0-9_.-]{1,64}` and must be unique among channels / patterns. Notes refer to
  channels by id; clips refer to patterns by id; `track` and `mixer` are array indices.
- A pattern clip longer than its pattern **loops** the pattern; `offset` shifts where it starts.
  Notes starting at or after the pattern `length` never play.
- Drum channels ignore note length (one-shots); pitch 60 plays the drum at its tuned pitch.
- Omitted `params`/`options` keys take their defaults (see catalog). Unknown keys are errors.
- Don't reorder `mixer.inserts` or `playlist.tracks` casually — other objects refer to them by index.
- Keep patterns musically self-contained (e.g. a 4-beat drum loop, a 16-beat bassline) and build
  the arrangement from clips; reuse patterns instead of duplicating notes.
- Colors are `#rrggbb`; the studio's palette favours golds, roses, champagne, burgundy, deep jewel tones.

## Musical craft

- Think like a producer: groove (velocity variation, swing), voice-leading in chords,
  frequency space (bass below ~200 Hz, pads filtered, hats high-passed), and arrangement
  energy (intro → build → drop → break → outro, changes every 8 or 16 bars).
- Check your work: `rosaclef render` reports peak/RMS. A healthy master peaks around −1 to
  −0.3 dBFS with the limiter; an RMS far below −20 dBFS usually means something is too quiet.
- Prefer editing parameters over adding effects; keep one `limiter` last on the master.

## Device catalog

{{CATALOG}}
"##;
