//! Factory presets for the `analog` engine (virtual analog).

use super::Preset;

pub const PRESETS: &[Preset] = &[
    Preset {
        name: "Sovereign Bronze Bass",
        kind: "analog",
        tags: "bass, analog, mono",
        doc: "Fat monophonic bass: detuned saw and pulse over a strong sub, driven into a warm, gently resonant ladder.",
        params: &[
            ("osc2Detune", -9.0),
            ("osc2Mix", 0.6),
            ("pulseWidth", 0.42),
            ("sub", 0.65),
            ("drift", 0.25),
            ("cutoff", 240.0),
            ("resonance", 0.35),
            ("drive", 0.55),
            ("keyTrack", 0.3),
            ("filterEnv", 0.33),
            ("filterDecay", 0.22),
            ("filterSustain", 0.1),
            ("attack", 0.002),
            ("decay", 0.5),
            ("sustain", 0.8),
            ("release", 0.08),
            ("glide", 0.035),
            ("gain", 0.8),
        ],
        options: &[("wave2", "pulse"), ("mode", "mono")],
    },
    Preset {
        name: "Wandering Silk Strings",
        kind: "analog",
        tags: "strings, warm, analog",
        doc: "Warm drifting string machine: two wide saws wandering against each other, a slow-opening filter and a long release.",
        params: &[
            ("osc2Detune", 13.0),
            ("osc2Mix", 0.8),
            ("sub", 0.0),
            ("drift", 0.75),
            ("cutoff", 1900.0),
            ("resonance", 0.12),
            ("drive", 0.15),
            ("keyTrack", 0.7),
            ("filterEnv", 0.15),
            ("filterAttack", 0.9),
            ("filterDecay", 1.6),
            ("filterSustain", 0.6),
            ("attack", 0.55),
            ("decay", 1.2),
            ("sustain", 0.85),
            ("release", 1.6),
            ("gain", 0.5),
        ],
        options: &[],
    },
    Preset {
        name: "Ruby Scream Lead",
        kind: "analog",
        tags: "lead, screaming, legato",
        doc: "Screaming legato lead: saw and octave pulse driven hard into the resonant screamer filter, with glide between tied notes.",
        params: &[
            ("osc2Semi", 12.0),
            ("osc2Detune", 5.0),
            ("osc2Mix", 0.4),
            ("pulseWidth", 0.32),
            ("sub", 0.0),
            ("drift", 0.35),
            ("cutoff", 1500.0),
            ("resonance", 0.82),
            ("drive", 0.75),
            ("keyTrack", 0.6),
            ("filterEnv", 0.35),
            ("filterDecay", 0.5),
            ("filterSustain", 0.4),
            ("attack", 0.004),
            ("decay", 0.4),
            ("sustain", 0.9),
            ("release", 0.2),
            ("glide", 0.07),
            ("gain", 0.5),
        ],
        options: &[("wave2", "pulse"), ("filter", "screamer"), ("mode", "legato")],
    },
    Preset {
        name: "Vermeil Fanfare Brass",
        kind: "analog",
        tags: "brass, poly, analog",
        doc: "Brassy polyphonic stabs: the filter swells open with each note, like a section taking a breath.",
        params: &[
            ("osc2Detune", 9.0),
            ("osc2Mix", 0.7),
            ("sub", 0.15),
            ("drift", 0.4),
            ("cutoff", 650.0),
            ("resonance", 0.2),
            ("drive", 0.45),
            ("keyTrack", 0.7),
            ("filterEnv", 0.42),
            ("filterAttack", 0.06),
            ("filterDecay", 0.45),
            ("filterSustain", 0.45),
            ("attack", 0.03),
            ("decay", 0.5),
            ("sustain", 0.8),
            ("release", 0.3),
            ("gain", 0.55),
        ],
        options: &[],
    },
    Preset {
        name: "Pearl Mist Pad",
        kind: "analog",
        tags: "pad, soft, analog",
        doc: "Soft analog pad: a hollow pulse and an octave triangle breathing through a slow, rounded filter.",
        params: &[
            ("osc2Semi", 12.0),
            ("osc2Detune", 4.0),
            ("osc2Mix", 0.55),
            ("pulseWidth", 0.3),
            ("sub", 0.2),
            ("noise", 0.04),
            ("drift", 0.6),
            ("cutoff", 900.0),
            ("resonance", 0.1),
            ("drive", 0.1),
            ("filterEnv", 0.2),
            ("filterAttack", 2.0),
            ("filterDecay", 3.0),
            ("filterSustain", 0.5),
            ("attack", 1.6),
            ("decay", 2.0),
            ("sustain", 0.9),
            ("release", 2.8),
            ("gain", 0.7),
        ],
        options: &[("wave1", "pulse"), ("wave2", "triangle")],
    },
    Preset {
        name: "Emerald Acid Bass",
        kind: "analog",
        tags: "bass, acid, squelch",
        doc: "Acid squelch: a single saw into a ladder on the edge of self-oscillation, snappy envelope and sliding legato notes.",
        params: &[
            ("osc2Mix", 0.0),
            ("sub", 0.0),
            ("drift", 0.15),
            ("cutoff", 280.0),
            ("resonance", 0.86),
            ("drive", 0.6),
            ("keyTrack", 0.3),
            ("filterEnv", 0.62),
            ("filterDecay", 0.18),
            ("filterSustain", 0.0),
            ("attack", 0.002),
            ("sustain", 0.6),
            ("release", 0.06),
            ("glide", 0.06),
            ("gain", 0.7),
        ],
        options: &[("mode", "legato")],
    },
    Preset {
        name: "Velvet Sub Bass",
        kind: "analog",
        tags: "bass, deep",
        doc: "Round filtered saw with a strong sine sub; sits under a four-on-the-floor kick.",
        params: &[
            ("osc2Semi", -12.0),
            ("osc2Detune", 7.0),
            ("osc2Mix", 0.35),
            ("sub", 0.6),
            ("drift", 0.0),
            ("cutoff", 340.0),
            ("drive", 0.0),
            ("keyTrack", 0.0),
            ("filterAttack", 0.001),
            ("filterDecay", 0.18),
            ("filterSustain", 0.0),
            ("attack", 0.003),
            ("decay", 0.25),
            ("sustain", 0.55),
            ("release", 0.08),
            ("gain", 0.89),
        ],
        options: &[("wave2", "pulse"), ("filter", "lowpass"), ("subWave", "sine")],
    },
    Preset {
        name: "Silk Unison Pad",
        kind: "analog",
        tags: "pad, lush",
        doc: "Five-voice unison saws, slow attack, gently filtered.",
        params: &[
            ("osc2Detune", 9.0),
            ("osc2Mix", 0.6),
            ("unison", 5.0),
            ("detune", 22.0),
            ("sub", 0.0),
            ("drift", 0.0),
            ("cutoff", 1300.0),
            ("resonance", 0.12),
            ("drive", 0.0),
            ("keyTrack", 0.0),
            ("filterEnv", 0.12),
            ("filterAttack", 0.001),
            ("filterDecay", 1.5),
            ("filterSustain", 0.0),
            ("attack", 1.4),
            ("decay", 1.5),
            ("sustain", 0.85),
            ("release", 2.4),
            ("gain", 0.34),
        ],
        options: &[("filter", "lowpass")],
    },
    Preset {
        name: "Gilded Lead",
        kind: "analog",
        tags: "lead, bright",
        doc: "Square and saw lead with a touch of glide.",
        params: &[
            ("osc2Semi", 12.0),
            ("osc2Detune", 7.0),
            ("osc2Mix", 0.3),
            ("unison", 3.0),
            ("detune", 10.0),
            ("sub", 0.0),
            ("drift", 0.0),
            ("cutoff", 3200.0),
            ("resonance", 0.25),
            ("drive", 0.0),
            ("keyTrack", 0.0),
            ("filterEnv", 0.3),
            ("filterAttack", 0.001),
            ("filterDecay", 0.4),
            ("filterSustain", 0.0),
            ("glide", 0.05),
            ("sustain", 0.8),
            ("release", 0.2),
            ("gain", 0.56),
        ],
        options: &[("wave1", "pulse"), ("filter", "lowpass")],
    },
];
