//! Factory presets for the original engines: Aurum (synth), Lumière (fm),
//! Atelier (drum).

use super::Preset;

pub const PRESETS: &[Preset] = &[
    Preset {
        name: "Velvet Sub Bass",
        kind: "synth",
        tags: "bass, deep",
        doc: "Round filtered saw with a strong sub; sits under a four-on-the-floor kick.",
        params: &[
            ("osc2Semi", -12.0),
            ("osc2Mix", 0.35),
            ("sub", 0.6),
            ("cutoff", 340.0),
            ("resonance", 0.3),
            ("filterEnv", 0.4),
            ("filterDecay", 0.18),
            ("attack", 0.003),
            ("decay", 0.25),
            ("sustain", 0.55),
            ("release", 0.08),
            ("gain", 0.8),
        ],
        options: &[("wave1", "saw"), ("wave2", "square")],
    },
    Preset {
        name: "Silk Unison Pad",
        kind: "synth",
        tags: "pad, lush",
        doc: "Five-voice unison saws, slow attack, gently filtered.",
        params: &[
            ("osc2Detune", 9.0),
            ("osc2Mix", 0.6),
            ("unison", 5.0),
            ("spread", 22.0),
            ("cutoff", 1300.0),
            ("resonance", 0.12),
            ("filterEnv", 0.12),
            ("filterDecay", 1.5),
            ("attack", 1.4),
            ("decay", 1.5),
            ("sustain", 0.85),
            ("release", 2.4),
            ("gain", 0.32),
        ],
        options: &[("wave1", "saw"), ("wave2", "saw")],
    },
    Preset {
        name: "Gilded Lead",
        kind: "synth",
        tags: "lead, bright",
        doc: "Square and saw lead with a touch of glide.",
        params: &[
            ("osc2Semi", 12.0),
            ("osc2Mix", 0.3),
            ("unison", 3.0),
            ("spread", 10.0),
            ("cutoff", 3200.0),
            ("resonance", 0.25),
            ("filterEnv", 0.3),
            ("filterDecay", 0.4),
            ("glide", 0.05),
            ("attack", 0.005),
            ("sustain", 0.8),
            ("release", 0.2),
            ("gain", 0.5),
        ],
        options: &[("wave1", "square"), ("wave2", "saw")],
    },
    Preset {
        name: "Rhodes Lumière",
        kind: "fm",
        tags: "keys, electric piano",
        doc: "Warm tine electric piano.",
        params: &[
            ("ratio", 1.0),
            ("index", 2.2),
            ("indexDecay", 0.9),
            ("velocity", 0.7),
            ("detune", 6.0),
            ("attack", 0.002),
            ("decay", 1.6),
            ("sustain", 0.3),
            ("release", 0.45),
            ("gain", 0.6),
        ],
        options: &[],
    },
    Preset {
        name: "Crystal Mallet",
        kind: "fm",
        tags: "bell, mallet",
        doc: "Bright inharmonic mallet for arpeggios.",
        params: &[
            ("ratio", 3.5),
            ("index", 2.4),
            ("indexDecay", 0.3),
            ("velocity", 0.5),
            ("detune", 3.0),
            ("attack", 0.001),
            ("decay", 0.45),
            ("sustain", 0.0),
            ("release", 0.35),
            ("gain", 0.45),
        ],
        options: &[],
    },
    Preset {
        name: "House Kick",
        kind: "drum",
        tags: "drums, kick",
        doc: "Punchy club kick.",
        params: &[
            ("tone", 0.35),
            ("snap", 0.55),
            ("decay", 1.1),
            ("tune", -1.0),
        ],
        options: &[("kind", "kick")],
    },
    Preset {
        name: "Satin Clap",
        kind: "drum",
        tags: "drums, clap",
        doc: "Wide layered clap.",
        params: &[("tone", 0.45), ("decay", 1.2)],
        options: &[("kind", "clap")],
    },
    Preset {
        name: "Champagne Hat",
        kind: "drum",
        tags: "drums, hat",
        doc: "Crisp closed hi-hat.",
        params: &[("tone", 0.62), ("decay", 0.9)],
        options: &[("kind", "hat")],
    },
];
