//! Factory presets for the `sextant` engine.

use super::Preset;

pub const PRESETS: &[Preset] = &[
    Preset {
        name: "Opaline Keys",
        kind: "sextant",
        tags: "keys, electric piano, glassy",
        doc: "Glassy tine electric piano: a warm body pair plus a bright, fast-fading tine that blooms with velocity.",
        params: &[
            ("op1Decay", 2.8),
            ("op1Sustain", 0.15),
            ("op2Level", 0.42),
            ("op2Decay", 1.6),
            ("op2Sustain", 0.2),
            ("op3Ratio", 1.0),
            ("op3Level", 0.55),
            ("op3Decay", 1.2),
            ("op3Sustain", 0.1),
            ("op4Ratio", 14.0),
            ("op4Level", 0.38),
            ("op4Decay", 0.18),
            ("op4Sustain", 0.0),
            ("op5Ratio", 1.0),
            ("op5Level", 0.3),
            ("op5Decay", 0.9),
            ("op5Sustain", 0.1),
            ("op6Ratio", 3.0),
            ("op6Level", 0.2),
            ("release", 0.6),
            ("velocity", 0.8),
            ("detune", 5.0),
            ("gain", 0.7),
        ],
        options: &[],
    },
    Preset {
        name: "Cathédrale d'Argent",
        kind: "sextant",
        tags: "bell, cinematic, long",
        doc: "Cathedral bell: an inharmonic strike over a hum an octave below, ringing for seconds.",
        params: &[
            ("op1Attack", 0.001),
            ("op1Decay", 6.0),
            ("op1Sustain", 0.0),
            ("op2Ratio", 3.5),
            ("op2Level", 0.45),
            ("op2Decay", 4.0),
            ("op2Sustain", 0.0),
            ("op3Ratio", 1.41),
            ("op3Level", 0.3),
            ("op3Decay", 2.0),
            ("op3Sustain", 0.0),
            ("op4Ratio", 0.5),
            ("op4Level", 0.7),
            ("op4Decay", 8.0),
            ("op4Sustain", 0.0),
            ("op5Ratio", 5.19),
            ("op5Level", 0.4),
            ("op5Decay", 1.5),
            ("op5Sustain", 0.0),
            ("op6Ratio", 7.07),
            ("op6Level", 0.25),
            ("op6Decay", 0.8),
            ("op6Sustain", 0.0),
            ("release", 4.0),
            ("feedback", 0.2),
            ("velocity", 0.5),
            ("detune", 2.0),
            ("gain", 0.75),
        ],
        options: &[("algorithm", "bell")],
    },
    Preset {
        name: "Obsidian Anvil",
        kind: "sextant",
        tags: "bass, metallic, aggressive",
        doc: "Metallic bass: a solid sine-core stack under a gritty, inharmonic mid stack with feedback.",
        params: &[
            ("op1Decay", 1.2),
            ("op1Sustain", 0.85),
            ("op2Decay", 0.4),
            ("op2Sustain", 0.35),
            ("op3Ratio", 1.0),
            ("op3Level", 0.3),
            ("op3Decay", 0.3),
            ("op4Ratio", 2.0),
            ("op4Level", 0.55),
            ("op4Decay", 0.6),
            ("op4Sustain", 0.6),
            ("op5Ratio", 3.5),
            ("op5Level", 0.55),
            ("op5Decay", 0.25),
            ("op5Sustain", 0.25),
            ("op6Level", 0.4),
            ("op6Decay", 0.8),
            ("op6Sustain", 0.4),
            ("release", 0.15),
            ("feedback", 0.6),
            ("velocity", 0.5),
            ("detune", 2.0),
            ("gain", 0.8),
        ],
        options: &[("algorithm", "twin")],
    },
    Preset {
        name: "Soleil Royal",
        kind: "sextant",
        tags: "brass, bright, lead",
        doc: "Bright brass: modulators swell in after the attack like a player leaning into the note.",
        params: &[
            ("op1Attack", 0.03),
            ("op1Decay", 0.5),
            ("op1Sustain", 0.85),
            ("op2Attack", 0.04),
            ("op2Decay", 0.6),
            ("op2Sustain", 0.9),
            ("op3Ratio", 1.0),
            ("op3Level", 0.5),
            ("op3Attack", 0.08),
            ("op3Decay", 0.4),
            ("op3Sustain", 0.6),
            ("op4Level", 0.45),
            ("op4Attack", 0.06),
            ("op4Decay", 0.6),
            ("op4Sustain", 0.5),
            ("op5Ratio", 1.0),
            ("op5Level", 0.35),
            ("op5Attack", 0.05),
            ("op5Decay", 0.6),
            ("op5Sustain", 0.6),
            ("op6Level", 0.35),
            ("op6Attack", 0.05),
            ("op6Decay", 0.6),
            ("op6Sustain", 0.6),
            ("release", 0.25),
            ("feedback", 0.6),
            ("velocity", 0.8),
            ("detune", 6.0),
            ("gain", 0.7),
        ],
        options: &[("algorithm", "brass")],
    },
    Preset {
        name: "Palissandre",
        kind: "sextant",
        tags: "mallet, marimba, percussive",
        doc: "Rosewood marimba: fundamental, tuned fourth and tenth partials, and a soft mallet strike.",
        params: &[
            ("op1Attack", 0.001),
            ("op1Decay", 0.9),
            ("op1Sustain", 0.0),
            ("op2Level", 0.35),
            ("op2Attack", 0.001),
            ("op2Decay", 0.05),
            ("op2Sustain", 0.0),
            ("op3Ratio", 4.0),
            ("op3Level", 0.35),
            ("op3Attack", 0.001),
            ("op3Decay", 0.25),
            ("op3Sustain", 0.0),
            ("op4Level", 0.2),
            ("op4Attack", 0.001),
            ("op4Decay", 0.05),
            ("op4Sustain", 0.0),
            ("op5Ratio", 10.0),
            ("op5Level", 0.12),
            ("op5Attack", 0.001),
            ("op5Decay", 0.08),
            ("op5Sustain", 0.0),
            ("op6Level", 0.0),
            ("velocity", 0.7),
            ("detune", 1.0),
            ("gain", 0.85),
        ],
        options: &[("algorithm", "triad")],
    },
    Preset {
        name: "Astrolabe Pluck",
        kind: "sextant",
        tags: "pluck, rhythmic, evolving",
        doc: "Rhythmic pluck whose modulators rise and fall at different rates, so repeated notes shimmer and shift.",
        params: &[
            ("op1Attack", 0.001),
            ("op1Decay", 0.6),
            ("op1Sustain", 0.0),
            ("op2Ratio", 2.0),
            ("op2Level", 0.55),
            ("op2Decay", 0.2),
            ("op2Sustain", 0.05),
            ("op3Ratio", 3.0),
            ("op3Level", 0.4),
            ("op3Attack", 0.06),
            ("op3Sustain", 0.1),
            ("op4Ratio", 2.0),
            ("op4Level", 0.6),
            ("op4Decay", 0.8),
            ("op4Attack", 0.001),
            ("op4Sustain", 0.0),
            ("op5Ratio", 4.0),
            ("op5Level", 0.4),
            ("op5Attack", 0.12),
            ("op5Decay", 0.3),
            ("op5Sustain", 0.1),
            ("op6Level", 0.35),
            ("op6Decay", 0.6),
            ("release", 0.3),
            ("feedback", 0.4),
            ("velocity", 0.7),
            ("detune", 8.0),
            ("gain", 0.75),
        ],
        options: &[("algorithm", "twin")],
    },
];
