//! Factory presets for the `wavetable` engine.

use super::Preset;

pub const PRESETS: &[Preset] = &[
    Preset {
        name: "Onyx Growl Bass",
        kind: "wavetable",
        tags: "bass, aggressive, growl",
        doc: "Heavy growl bass: FM wavetable swept by LFO and envelope, bent, driven hard over a clean sine sub.",
        params: &[
            ("position", 0.2),
            ("positionEnv", 0.3),
            ("positionLfo", 0.6),
            ("lfoRate", 2.0),
            ("warp", 0.3),
            ("unison", 2.0),
            ("detune", 10.0),
            ("width", 0.4),
            ("sub", 0.6),
            ("cutoff", 1800.0),
            ("resonance", 0.35),
            ("filterEnv", 0.3),
            ("modDecay", 0.4),
            ("drive", 0.6),
            ("attack", 0.003),
            ("decay", 0.4),
            ("sustain", 0.9),
            ("release", 0.12),
            ("gain", 0.7),
        ],
        options: &[("table", "growl"), ("warp", "bend")],
    },
    Preset {
        name: "Aurora Supersaw Lead",
        kind: "wavetable",
        tags: "lead, wide, supersaw",
        doc: "Wide supersaw lead: seven detuned saws spread across the stereo field.",
        params: &[
            ("position", 0.5),
            ("unison", 7.0),
            ("detune", 38.0),
            ("width", 1.0),
            ("cutoff", 9000.0),
            ("resonance", 0.15),
            ("filterEnv", 0.2),
            ("modDecay", 0.5),
            ("sustain", 0.85),
            ("release", 0.35),
            ("gain", 0.6),
        ],
        options: &[],
    },
    Preset {
        name: "Celestial Veil Pad",
        kind: "wavetable",
        tags: "pad, ethereal, evolving",
        doc: "Ethereal pad: glassy partials drifting slowly along the table, mirrored and spread wide.",
        params: &[
            ("position", 0.3),
            ("positionLfo", 0.35),
            ("lfoRate", 0.12),
            ("warp", 0.3),
            ("unison", 5.0),
            ("detune", 20.0),
            ("width", 1.0),
            ("cutoff", 4500.0),
            ("attack", 1.5),
            ("decay", 2.0),
            ("sustain", 0.8),
            ("release", 3.0),
            ("gain", 0.9),
        ],
        options: &[("table", "glass"), ("warp", "mirror")],
    },
    Preset {
        name: "Quartz Shard Pluck",
        kind: "wavetable",
        tags: "pluck, crisp, bright",
        doc: "Crisp pluck: sparse digital harmonic combs snapping shut under a fast filter envelope.",
        params: &[
            ("position", 0.9),
            ("positionEnv", -0.3),
            ("detune", 10.0),
            ("cutoff", 2500.0),
            ("resonance", 0.3),
            ("filterEnv", 0.5),
            ("modDecay", 0.15),
            ("attack", 0.001),
            ("decay", 0.4),
            ("sustain", 0.0),
            ("gain", 1.2),
        ],
        options: &[("table", "digital")],
    },
    Preset {
        name: "Sapphire Vowel Pad",
        kind: "wavetable",
        tags: "vocal, texture, pad",
        doc: "Formant texture: a slow LFO walks the vowels while three voices breathe around each other.",
        params: &[
            ("position", 0.1),
            ("positionLfo", 0.5),
            ("lfoRate", 0.25),
            ("detune", 12.0),
            ("cutoff", 6000.0),
            ("attack", 0.25),
            ("sustain", 0.85),
            ("release", 1.2),
            ("gain", 0.6),
        ],
        options: &[("table", "vocal")],
    },
    Preset {
        name: "Amber Velvet Poly",
        kind: "wavetable",
        tags: "poly, warm, analog",
        doc: "Warm analog-style poly: saw-to-square blend, gentle filter envelope and a touch of drive.",
        params: &[
            ("position", 0.55),
            ("positionLfo", 0.08),
            ("lfoRate", 0.3),
            ("unison", 2.0),
            ("detune", 9.0),
            ("cutoff", 1400.0),
            ("resonance", 0.2),
            ("filterEnv", 0.35),
            ("modDecay", 0.7),
            ("drive", 0.2),
            ("attack", 0.01),
            ("decay", 0.6),
            ("release", 0.5),
            ("gain", 0.6),
        ],
        options: &[],
    },
];
